### ISSUE TITLE
Actualizar step multistream con scribe (Refactor xmatch step)

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/xmatch_step#29]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/xmatch_step/issues/30
- [ ] https://github.com/alercebroker/xmatch_step/issues/32
- [ ] https://github.com/alercebroker/kubernetes_pipeline/issues/33
- [ ] https://github.com/alercebroker/xmatch_step/issues/36
```

- Calcular meanra a partir de las detecciones
- Enviar request de CDS usando ra, dec (mean)
- Producir xmatch, detecciones y no-detecciones

# Criterios de aceptación 

- Debe funcionar para ATLAS (ignorándolas) y ZTF
- Debe consumir en batch desde tópico de curva de luz, producido por [Detection Step](https://github.com/alercebroker/detection_step)
- Debe producir a un tópico de resultados (xmatch) con la curva de luz y xmatch del objeto.
- Debe producir métricas de prometheus por HTTP en el endpoint host:8000/metrics

# Criterios de aceptación no funcionales
- El deployment debe incluir HPA usando métricas de `consumed_messages`
- El deployment se debe hacer mediante helm chart
